project:
  type: website

website:
  title: "Haley Puddy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - project.qmd
      - href: CV.pdf
        text: CV
      - assignments.qmd
      - menu: 
        - assign01.qmd
        - assign02.qmd
      

format:
  html:
    theme: journal
    css: styles.css
    toc: true