---
title: "CV"
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
---

# EDUCATION

Doctor of Philosophy in Criminology, The University of Texas at Dallas (2022- Current)

Master of Science in Criminology and Criminal Justice, The University of Texas at Dallas (2022); Thesis Title: Public Perceptions of the Connection between Immigration and Crime

Bachelor of Arts in Psychology (Magna Cum Laude), Loyola University Maryland (2019)

# RESEARCH & TEACHING EXPERIENCE

University of Texas at Dallas, Richardson, TX School of Economic, Political, and Policy Sciences Teaching Assistant (Aug 2022-Current) • Introduction to Criminal Justice

University of Texas at Dallas, Richardson, TX School of Arts, Technology, and Emerging Communication Student Research Assistant (Feb 2021-Aug 2021) • Dr. Rosanna Guadagno, Ph.D.

Johns Hopkins University School of Medicine, Baltimore, MD Department of Psychiatry and Behavioral Sciences Research Program Assistant II (Jan 2019-June 2020) • Dr. Kelly Dunn, Ph.D., M.B.A.; Dr. Alexis Hammond, M.D., Ph.D.

Loyola University Maryland, Baltimore, MD Research Assistant (Nov 2018- May 2019) • Dr. Marianna Carlucci; Dr. Amy Wolfson

Parkland Hospital- Dallas, TX College Research Intern (Jun 2018-Aug 2018)

# ORGANIZATIONS

Criminology Graduate Student Association, The University of Texas at Dallas, Student Member (2020-22), Board Member (2022-Current)

# PROFESSIONAL CERTIFICATIONS/TRAININGS

Fundamentals of Research Coordination, Johns Hopkins University

Green Dot Bystander Intervention, Loyola University Maryland

# PROFESSIONAL AFFILIATIONS

Psi Chi

American College Health Association

# RESEARCH PRESENTATIONS

Puddy, H. N., Wilton, S., (2019). The Role of Empathy in the Perception of Racial Inequalities in the Criminal Justice System. Paper presented at the annual Undergraduate Student Research & Scholarship Colloquium (USRSC), Loyola University Maryland, Baltimore, MD (1st place)

# SCHOLARLY EXPERIENCE & PUBLICATIONS

Puddy, H. N. (2022). Public Perceptions of the Connection Between Immigration and Crime. Master's Thesis; Presented to the faculty of the University of Texas at Dallas in partial fulfillment of the requirements for the degree of Master of Science in Criminology

Guadagno, R. E.; Gonzenbach, V.; Puddy, H.; Fishwick, P.; Kitagawa, M.; Urquhart, M.; Kesden, M.; Suura, K.; Hale, B.; Koknar, C.; et al. A Usability Study of Classical Mechanics Education Based on Hybrid Modeling: Implications for Sustainability in Learning. Sustainability 2021, 13, 11225. https://doi.org/10.3390/su132011225

Puddy, H. N., Wilton, S., (2019). The Role of Empathy in the Perception of Racial Inequalities in the Criminal Justice System. Honors Thesis; Presented at USRSC Colloquium at Loyola University Maryland on April 5th, 2019.

Guido, A., Kazalas, A., Puddy, H. N., Rohan, D., & Wilton, S., (2017). Looking for Mr. (or Mrs.) Right: Consistency of Personality Traits in Emerging Adults for Romantic Relationships. Research Project; Presented to Loyola University Maryland Psychology Department
